### ISSUE TITLE
Player lookup with warzone player uuid

### ISSUE THREAD

**Issue by MattBSG** [WarzoneMC/API#11]
Currently, the punishments route does not return punisher's `name` but instead a `uuid` representing the staff member responsible. For certain integrations this should either return the responsible punisher's `name` or an amended [lookup endpoint](https://github.com/WarzoneMC/API/blob/master/routes/minecraft/players.js#L140) that can return player info (including an IGN) of a provided player uuid be created.

**Comment by jorgeberrex** [comment]
Edited punishments enpoint https://github.com/WarzoneMC/API/commit/0937f8ccc52d4ec6486974abdde4f9b7fc05395a
